sistema/livros/models.py
from sistema import db

Disponibilidade = db.Table('disponibilidade',
                           db.Column('livro_id', db.Integer, db.ForeignKey('livro.id')),
                           db.Column('sede_id', db.Integer, db.ForeignKey('sede.id')))

class Livro(db.Model):
    __tablename__ = 'livro'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    gender = db.Column(db.String)
    author = db.Column(db.String)
    price = db.Column(db.String)
    pub_date = db.Column(db.String)
    available = db.Column(db.Boolean)
    cover = db.Column(db.String)
    sedes = db.relationship('Sede', secondary=Disponibilidade, back_populates='livros')

    def __init__(self, title, gender, author, price, pub_date, available, cover):
        self.title = title
        self.gender = gender
        self.author = author
        self.price = price
        self.pub_date = pub_date
        self.available = available
        self.cover = cover

    def __repr__(self):
        return f'<Livro {self.title}>'

sistema/livros/views.py
import os
from flask import Blueprint, render_template, request, redirect, url_for
from sistema import app, db, allowed_image
from sistema.livros.models import Livro
from sistema.sedes.models import Sede
from werkzeug.utils import secure_filename

livros = Blueprint('livros', __name__, template_folder="templates")


@livros.route('/')
def index():
    livros = Livro.query.order_by(Livro.id.desc()).all()
    return render_template('livros.html', livros=livros)


@livros.route('/livro-esp/<_id>')
def livro_esp(_id):
    livro = Livro.query.get_or_404(_id)
    len_sedes = len(Sede.query.order_by(Sede.id.desc()).all())
    len_livro_sedes = len(livro.sedes)
    if len_livro_sedes == len_sedes:
        livro_todas = True
    else:
        livro_todas = False
    return render_template('livro_esp.html', livro=livro, livro_todas = livro_todas)


@livros.route('/adicionar-livro/', methods=['GET', 'POST'])
def adicionar_livro():
    sedes = Sede.query.order_by(Sede.id.asc()).all()
    if request.method == 'POST':
        titulo = request.form['title']
        genero = request.form['gender']
        autor = request.form['author']
        date = request.form['date']
        price = request.form['price']
        # É necessário converter as checkboxes em booleans, porque elas retornam strings.
        available = False
        if request.form.get('available') == 'on':
            available = True
        # Método para converter o "price" para o modelo "R$ XX,XX"
        price.strip()
        price = price.replace(".", ",")
        price = price.replace("r", "R")
        if price.startswith('R$') and not price.startswith('R$ '):
            price = price.replace('R$', 'R$ ')
        if price.startswith('R$') and ',' not in price:
            price = price + ',00'
        if not price.startswith('R$'):
            if price.startswith(' '):
                price = "R$" + price
            else:
                price = "R$ " + price
        if not price.startswith('R$') and ',' not in price:
            if price.startswith(' '):
                price = "R$" + price
            else:
                price = "R$ " + price
            price = price + ',00'
        if ',' not in price:
            price = price + ',00'

        # Limpando espaço duplo
        price = price.replace("  ", " ")

        image = request.files['myfile']

        sedes_associadas = []
        for sede in sedes:
            select = request.form.get('availableAt' + str(sede.id))
            print(select)
            if select == "on":
                sede_adicionada = Sede.query.get_or_404(sede.id)
                if sede_adicionada not in sedes_associadas:
                    sedes_associadas.append(sede_adicionada)

        if not allowed_image(image.filename):
            print("That image is not allowed")
            return redirect(url_for('livros.adicionar_livro'))
        else:
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config["IMAGE_UPLOADS"], filename))
            livro = Livro(titulo, genero, autor, price, date, available, filename)
            if request.form.get('linked') != 'on':
                livro.sedes = []
            else:
                livro.sedes = sedes_associadas
            db.session.add(livro)
            db.session.commit()
            return redirect(url_for('livros.index'))

    return render_template('adicionar-livro.html', sedes = sedes)


@livros.route('/editar_livro/<_id>', methods=['GET', 'POST'])
def editar_livro(_id):

    livro = Livro.query.get_or_404(_id)
    sedes = Sede.query.order_by(Sede.id.asc()).all()

    if request.method == 'POST':
        title = request.form['title']
        author = request.form['author']
        gender = request.form['gender']
        date = request.form['date']
        price = request.form['price']
        # É necessário converter as checkboxes em booleans, porque elas retornam strings.
        available = False
        if request.form.get('available') == 'on':
            available = True
        # Método para converter o "price" para o modelo "R$ XX,XX"
        price.strip()
        price = price.replace(".", ",")
        price = price.replace("r", "R")
        if price.startswith('R$') and not price.startswith('R$ '):
            price = price.replace('R$', 'R$ ')
        if price.startswith('R$') and ',' not in price:
            price = price + ',00'
        if not price.startswith('R$'):
            if price.startswith(' '):
                price = "R$" + price
            else:
                price = "R$ " + price
        if not price.startswith('R$') and ',' not in price:
            if price.startswith(' '):
                price = "R$" + price
            else:
                price = "R$ " + price
            price = price + ',00'
        if ',' not in price:
            price = price + ',00'

        # Limpando espaço duplo
        price = price.replace("  ", " ")

        image = request.files['myfile']

        sedes_associadas = []
        for sede in sedes:
            select = request.form.get('availableAt' + str(sede.id))
            if select == "on":
                sede_adicionada = Sede.query.get_or_404(sede.id)
                if sede_adicionada not in sedes_associadas:
                    sedes_associadas.append(sede_adicionada)
            else:
                sede_adicionada = Sede.query.get_or_404(sede.id)
                if sede_adicionada in sedes_associadas:
                    sedes_associadas.remove(sede_adicionada)


        if not allowed_image(image.filename) and image:
            print("That image is not allowed")
            return redirect(url_for('livros.editar_livro', _id=livro.id))
        elif image:
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config["IMAGE_UPLOADS"], filename))

            livro.title = title
            livro.author = author
            livro.gender = gender
            livro.pub_date = date
            livro.price = price
            livro.available = available
            livro.cover = filename
            if request.form.get('linked') != 'on':
                livro.sedes = []
            else:
                livro.sedes = sedes_associadas
            db.session.commit()

            return redirect(url_for('livros.livro_esp', _id=livro.id))
        else:
            livro.title = title
            livro.author = author
            livro.gender = gender
            livro.pub_date = date
            livro.price = price
            livro.available = available
            if request.form.get('linked') != 'on':
                livro.sedes = []
            else:
                livro.sedes = sedes_associadas

            db.session.commit()
            return redirect(url_for('livros.livro_esp', _id=livro.id))

    return render_template('editar_livro.html', livro=livro, sedes=sedes)


@livros.route('/excluir_livro/<_id>', methods=['GET', 'POST'])
def excluir_livro(_id):
    livro = Livro.query.get_or_404(_id)

    if request.method == 'POST':
        db.session.delete(livro)
        db.session.commit()

        return redirect(url_for('livros.index'))
    return render_template('excluir_livro.html', livro=livro)

sistema/livros/templates/adicionar-livro.html
{% extends 'base.html' %}

{% block body %}
        <main>
            <main>
                <div class="container">
                    <div  class="form-group d-flex flex-fill justify-content-center">
                        <form class="form-livros mobile-wider" action="" method="POST" enctype="multipart/form-data">
                            <div class="input-wrapper">
                                <label for="title">Título</label>
                                <input type="text" name="title" id="title" placeholder="Digite aqui o título do livro a ser adicionado." required>
                            </div>
                            <div class="input-wrapper">
                                <label for="author">Autor</label>
                                <input type="text" name="author" id="author" placeholder="Insira aqui o nome do autor do livro." required>
                            </div>
                            <div class="input-wrapper">
                                <label for="gender">Gênero</label>
                                <input type="text" name="gender" id="gender" placeholder="Ex: Romance." required>
                            </div>
                            <div class="input-wrapper">
                                <label for="date">Ano de Publicação</label>
                                <input class="data-livros" type="text" name="date" id="date" placeholder="1991" required>
                            </div>
                            <div class="input-wrapper">
                                <label for="price">Preço</label>
                                <input type="text" name="price" id="price" placeholder="R$ 00,00." required>
                            </div>
                            <div class="textarea-branco">
                                <div class="input-wrapper upload-btn">
                                    <label for="foto-livro" style="margin-bottom: 0px;">Adicionar capa do livro</label>
                                    <input type="file" id="myfile" name="myfile" required>
                                </div>
                            </div>
                            <!-- DISPONÍVEL / REGISTRADO -->
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="available" name="available">
                                <label class="custom-control-label" for="available">Disponível em estoque?</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="customCheck2" name="linked">
                                <label class="custom-control-label" for="customCheck2">Registrar em sede?</label>
                            </div>
                            <!-- Lista de Sedes -->
                            <div id="lista-sedes">
                                <div style="padding-left: 50px;">
                                    {% for sede in sedes %}
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="availableAt{{sede.id}}" name="availableAt{{sede.id}}">
                                        <label class="custom-control-label" for="availableAt{{sede.id}}">{{sede.name}}</label>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <br>
                            <input class="btn-primary" type="submit" value="Adicionar novo livro"> 
                        </form>
                    </div>
                </div>
            </main>
        </main>
        <!-- FUNÇÃO PARA MOSTRAR O DROPDOWN DAS SEDES -->
        <script type="text/javascript">
            $(document).ready(function(){
                $("#customCheck2").click(function(){
                  $("#lista-sedes").toggle();
                  $("#addSede").toggle();
                  
                });
              });

        </script>

{% endblock %}

sistema/livros/templates/editar_livro.html
{% extends 'base.html' %}

{% block body %}
        <main>
            <main>
                <div class="container">
                    <div  class="form-group d-flex flex-fill justify-content-center">
                        <form class="form-livros mobile-wider" action="" method="POST" enctype="multipart/form-data">
                            <div class="input-wrapper">
                                <label for="title">Título</label>
                                <input type="text" name="title" id="title" placeholder="Digite aqui o título do livro a ser adicionado." value="{{livro.title}}" required>
                            </div>
                            <div class="input-wrapper">
                                <label for="author">Autor</label>
                                <input type="text" name="author" id="author" placeholder="Insira aqui o nome do autor do livro." value="{{livro.author}}" required>
                            </div>
                            <div class="input-wrapper">
                                <label for="gender">Gênero</label>
                                <input type="text" name="gender" id="gender" placeholder="Ex: Romance." value="{{livro.gender}}" required>
                            </div>
                            <div class="input-wrapper">
                                <label for="date">Ano de Publicação</label>
                                <input class="data-livros" type="text" name="date" id="date" placeholder="1991" value="{{livro.pub_date}}" required>
                            </div>
                            <div class="input-wrapper">
                                <label for="price">Preço</label>
                                <input type="text" name="price" id="price" placeholder="R$ 00,00." value="{{livro.price}}" required>
                            </div>
                            <div class="textarea-branco">
                                <div class="input-wrapper upload-btn">
                                    <label for="foto-livro" style="margin-bottom: 0px;">Modificar capa do livro</label>
                                    <input type="file" id="myfile" name="myfile">
                                </div>
                            </div>
                            <!-- DISPONÍVEL / REGISTRADO -->
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="available" name="available" {%if livro.available%}checked{%endif%}>
                                <label class="custom-control-label" for="available">Disponível em estoque?</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="customCheck2" name="linked"  {% if livro.sedes != [] %}checked{% endif %} >
                                <label class="custom-control-label" for="customCheck2">Registrar em sede?</label>
                            </div>
                            <!-- Lista de Sedes -->
                            <div id="lista-sedes-edit">
                                <div style="padding-left: 50px;">
                                    {% for sede in sedes %}
                                    <div class="custom-control custom-checkbox">
                                        <input {% if sede in livro.sedes%} checked {% endif %} type="checkbox" class="custom-control-input" id="availableAt{{sede.id}}" name="availableAt{{sede.id}}">
                                        <label class="custom-control-label" for="availableAt{{sede.id}}">{{sede.name}}</label>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <br>
                            <input class="btn-primary" type="submit" value="Atualizar livro"> 
                        </form>
                    </div>
                </div>
            </main>
        </main>
        <!-- FUNÇÃO PARA MOSTRAR O DROPDOWN DAS SEDES -->
        <script type="text/javascript">
            $(document).ready(function(){
                if(document.getElementById("customCheck2").checked == true){
                    document.getElementById("lista-sedes-edit").style.display = 'block';
                } else {
                    document.getElementById("lista-sedes-edit").style.display = 'none';
                }
                $("#customCheck2").click(function(){
                    if(document.getElementById("customCheck2").checked == true){
                        document.getElementById("lista-sedes-edit").style.display = 'block';
                    } else {
                        document.getElementById("lista-sedes-edit").style.display = 'none';
                    }
                    
                });
              });
        </script>

{% endblock %}

sistema/livros/templates/excluir_livro.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div  class="form-group d-flex flex-fill justify-content-center">
        <div class="input-wrapper" >
            <br><br><br><br>
            <div style="display: flex; justify-content: center;">
                <h1 class="titulo-excluir">Você tem certeza que quer excluir "{{livro.title}}"?</h1>
            </div>
            <br><br>
            <form action="" method="POST" enctype="multipart/form-data">
                <input type="submit" value="Sim!" class="btn btn-primary botoes-excluir excluir-sim">
                <br>
                <a href="{{url_for('livros.livro_esp', _id=livro.id)}}" class="btn btn-primary botoes-excluir btn-block" style="margin-top: 6px;">Não!</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sistema/livros/templates/livro_esp.html
{% extends 'base.html' %}

{% block body %}

    <main>
        <div class="container">
            <br>
            <!--Duas div, a primeira contendo a imagem do livro, a segunda informações-->
            <div class="row">
                <div class="col-sm-6 capa-livro">
                    <img src="{{url_for('static', filename='images/' + livro.cover)}}" alt="" height="400px" class="rounded img-in-div-livros">
                </div>
                <div class="livro-info col-sm-6">
                            <h2 class="montserrat mobile-center" style="margin-bottom: 20px;">{{livro.title}}</h2>

                            <h4>AUTOR</h4>
                            <p>{{livro.author}}</p>

                            <h4>GÊNERO</h4>
                            <p>{{livro.gender}}</p>

                            <h4>PUBLICAÇÃO</h4></td>
                            <p>{{livro.pub_date.replace('-', '/')}}</p>

                            <h4>DISPONIBILIDADE</h4>
                            <p>{% if livro.available %}Disponível{% endif %}{% if not livro.available%}Indisponível{% endif %}{% if livro.sedes != [] %}. Registrado em {% endif %}
                                {% if livro_todas %}
                                todas as sedes.
                                {% else %}
                                {% for sede in livro.sedes %}
                                    {% if sede != livro.sedes[-1] and sede != livro.sedes[-2] %}
                                    {{sede.name}}, 
                                    {% endif %}
                                    {% if sede != livro.sedes[-1] and sede == livro.sedes[-2] %}
                                    {{sede.name}} 
                                    {% endif %}
                                    {% if sede == livro.sedes[-1] and sede != livro.sedes[0] %}
                                    e {{sede.name}}.
                                    {% endif %}
                                    {% if sede == livro.sedes[-1] and sede == livro.sedes[0] %}
                                    {{sede.name}}.
                                    {% endif %}
                                {% endfor %}
                                {% endif %}
                            </p>
                            <h4>PREÇO</h4>
                            <p>{{livro.price}}</p>

                    </table>
                    <!--Botões excluir e editar-->
                    <div class="mobile-flex-center">
                        <a href="{{url_for('livros.editar_livro', _id=livro.id)}}"><button type="button" class="btn btn-primary">Editar</button></a>
                        <a href="{{url_for('livros.excluir_livro', _id=livro.id)}}"><button type="button" class="mobile-pad-left btn btn-primary">Excluir</button></a>
                    </div>
                </div>
            </div>
            <br>
            <br>
        </div>
    </main>

{% endblock %}

sistema/livros/templates/livros.html
{% extends 'base.html' %}

{% block body %}

    <main>
        <div class="container cardboard-livros container-livros-mobile">
            <br>
            <h2 class="montserrat" style="display: inline;">LIVROS</h2>
            <div class="adicionar-livro">
                <a href="{{url_for('livros.adicionar_livro')}}" class="button-link"><button type="button" class="btn btn-primary">Adicionar</button></a>
            </div>
            <br>
            <br>
            <br>
        <!--Cards-->
            {% if not livros %}
            <h2>Ainda não há livros registrados</h2>
            {% endif %}
            <div class="row row-mobile" style="justify-content: center;">
                {% for livro in livros %}

                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <a class="no-dec" href="{{url_for('livros.livro_esp', _id=livro.id)}}"><p class="card-text">{{livro.title}}</p></a>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">{{livro.gender}} - {{livro.author}}</p>
                            </div>
                        </div>
                        <img src="{{url_for('static', filename='images/' + livro.cover)}}">
                        <div class="card-body">
                            <p class="card-text">{{livro.price}}</p>
                        </div>
                    </div>
                </div>

                {% endfor %}


            </div>
            <!--<div class="row row-mobile">
                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <p class="card-text">Drácula</p>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">Terror - Bram Stoker</p>
                            </div>
                        </div>
                        <img src="https://image.ibb.co/bSkLh9/unnamed_1.png">
                        <div class="card-body">
                            <p class="card-text">R$ 60,99</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <p class="card-text">Frankenstein</p>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">Terror - Mary Shelley</p>
                            </div>
                        </div>
                        <img src="https://images-na.ssl-images-amazon.com/images/I/A1bvtg4uwdL.jpg">
                        <div class="card-body">
                            <p class="card-text">R$ 59,90</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <p class="card-text">Medo Clássico Vol. 1</p>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">Terror - Edgar Alan Poe</p>
                            </div>
                        </div>
                        <img src="../static/images/medo_classico_vol1.jpg">
                        <div class="card-body">
                            <p class="card-text">R$ 50,92</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <p class="card-text">Medo Clássico Vol. 2</p>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">Terror - Edgar Alan Poe</p>
                            </div>
                        </div>
                        <img src="https://image.isu.pub/181109163529-8dabdb9a3942c008630f27845d35be2f/jpg/page_1.jpg">
                        <div class="card-body">
                            <p class="card-text">R$ 59,90</p>
                        </div>
                    </div>
                </div>
            </div> -->
            <br>
            </div>
    </main>

{% endblock %}