sistema/novidades/models.py
from sistema import db
from datetime import datetime


class Novidade(db.Model):
    __tablename__ = 'novidade'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    content = db.Column(db.String)
    author = db.Column(db.String)
    pub_date = db.Column(db.String)

    def __init__(self, title, content, author):
        self.title = title
        self.content = content
        self.author = author

    def __repr__(self):
        return f'<Novidade {self.title}>'

sistema/novidades/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from sistema import db
from sistema.novidades.models import Novidade
from datetime import datetime
import locale
try:
    locale.setlocale(locale.LC_ALL, 'pt_BR')
except:
    locale.setlocale(locale.LC_ALL, 'Portuguese_Brazil')

novidades = Blueprint('novidades', __name__, template_folder="templates")

@novidades.route('/')
def index():
    novidades = Novidade.query.order_by(Novidade.id.desc()).all()
    return render_template('novidades.html', novidades_front=novidades)


@novidades.route('/adicionar-novidade/', methods=['GET', 'POST'])
def adicionar_novidade():
    if request.method == 'POST':
        titulo = request.form['title']
        mensagem = request.form['mensagem']
        nome = request.form['nome']

        novidade = Novidade(titulo, mensagem, nome)
        db.session.add(novidade)
        datenow = datetime.utcnow()
        novidade.pub_date = datenow.strftime('%x')
        # split_date = novidade.pub_date.split(" ", 1)
        # novidade.pub_date = split_date[0].replace('-', '/')

        db.session.commit()
        return redirect(url_for('novidades.index'))

    return render_template('adicionar-novidade.html')


@novidades.route('/editar_novidade/<_id>', methods=['GET', 'POST'])
def editar_novidade(_id):
    novidade = Novidade.query.get_or_404(_id)

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['mensagem']
        author = request.form['nome']

        novidade.title = title
        novidade.content = content
        novidade.author = author

        db.session.commit()

        return redirect(url_for('novidades.index'))

    return render_template('editar_novidade.html', novidade=novidade)


@novidades.route('/excluir_novidade/<_id>', methods=['GET', 'POST'])
def excluir_novidade(_id):
    novidade = Novidade.query.get_or_404(_id)

    if request.method == 'POST':
        db.session.delete(novidade)
        db.session.commit()

        return redirect(url_for('novidades.index'))
    return render_template('excluir_novidade.html', novidade=novidade)

sistema/novidades/templates/adicionar-novidade.html
{% extends 'base.html' %}

{% block body %}
    <main>
        <div class="container">
            <div  class="form-group d-flex flex-fill justify-content-center">
                <form class="form-livros mobile-wider" action="" method="POST">
                    <div class="input-wrapper">
                        <label for="title">Título</label>
                        <input type="text" name="title" id="title" placeholder="Título da novidade.">
                    </div>
                    <div class="input-wrapper">
                        <label for="mensagem">Mensagem</label>
                        <textarea name="mensagem" id="mensagem" cols="30" rows="10" placeholder="Escreva aqui a sua mensagem."></textarea>
                    </div>
                    <div class="input-wrapper">
                        <label for="nome">Autor</label>
                        <input type="text" name="nome" id="nome" placeholder="Escreva seu nome aqui.">
                    </div>
                    <br>
                    <input class="btn-primary" type="submit" value="Adicionar novidade">
                </form>
            </div>
        </div>
    </main>
{% endblock %}

sistema/novidades/templates/editar-novidade.html
{% extends 'base.html' %}

{% block body %}
    <main>
        <div class="container">
            <div  class="form-group d-flex flex-fill justify-content-center">
                <form class="form-livros mobile-wider" action="/" method="POST">
                    <div class="input-wrapper">
                        <label for="mensagem">Mensagem</label>
                        <textarea name="mensagem" cols="30" rows="10" placeholder="Escreva aqui a sua mensagem."></textarea>
                    </div>
                    <div class="input-wrapper">
                        <label for="nome">Autor</label>
                        <input type="text" name="name" placeholder="Escreva seu nome aqui.">
                    </div>
                    <br>
                    <input class="btn-primary" type="submit" value="Adicionar novidade">
                </form>
            </div>
        </div>
    </main>
{% endblock %}

sistema/novidades/templates/editar_novidade.html
{% extends 'base.html' %}

{% block body %}
    <main>
        <div class="container">
            <div  class="form-group d-flex flex-fill justify-content-center">
                <form class="form-livros mobile-wider" action="" method="POST">
                    <div class="input-wrapper">
                        <label for="title">Título</label>
                        <input type="text" name="title" id="title" placeholder="Título da novidade." value="{{novidade.title}}">
                    </div>
                    <div class="input-wrapper">
                        <label for="mensagem">Mensagem</label>
                        <textarea name="mensagem" id="mensagem" cols="30" rows="10" placeholder="Escreva aqui a sua mensagem.">{{novidade.content}}</textarea>
                    </div>
                    <div class="input-wrapper">
                        <label for="nome">Autor</label>
                        <input type="text" name="nome" id="nome" placeholder="Escreva seu nome aqui." value="{{novidade.author}}">
                    </div>
                    <br>
                    <input class="btn-primary" type="submit" value="Atualizar novidade">
                </form>
            </div>
        </div>
    </main>
{% endblock %}

sistema/novidades/templates/excluir_novidade.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div  class="form-group d-flex flex-fill justify-content-center">
        <div class="input-wrapper" >
            <br><br><br><br>
            <div style="display: flex; justify-content: center;">
                <h1 class="titulo-excluir">Você tem certeza que quer excluir "{{novidade.title}}"?</h1>
            </div>
            <br><br>
            <form action="" method="POST" enctype="multipart/form-data">
                <input type="submit" value="Sim!" class="btn btn-primary botoes-excluir excluir-sim">
                <br>
                <a href="{{url_for('novidades.index')}}" class="btn btn-primary botoes-excluir btn-block">Não!</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sistema/novidades/templates/novidades.html
{% extends 'base.html' %}

{% block body %}

    <main>
        <div class="container">
            <br>
            <h2 class="montserrat" style="float: left;">NOVIDADES</h2>
            <div class="adicionar-livro">
                <a href="{{url_for('novidades.adicionar_novidade')}}" class="button-link"><button type="button" class="btn btn-primary">Adicionar</button></a>
            </div>
            <br>
            <br>
            <br>
        <div class="col-sm-12" style="padding-left: 0px;">
            {% if not novidades_front %}
            <h3>Ainda não há novidades adicionadas.</h3>
            {% endif %}
            {% for novidade in novidades_front %}
            <div class="novidade">
                <h4>{{novidade.title}}</h4>
                <p>{{novidade.content}}</p>
                <div class="nome-data-novidade">
                    <p><strong>{{novidade.author}}, {{novidade.pub_date}}</strong></p>
                    
                    <a href="{{url_for('novidades.editar_novidade', _id=novidade.id)}}" class="button-link"><button type="button" class="btn btn-primary">Editar</button></a>
                    <a href="{{url_for('novidades.excluir_novidade', _id=novidade.id)}}" class="button-link"><button type="button" class="btn btn-primary">Excluir</button></a>
                    
                </div>
                <br class="mobile-header">
            {% endfor %}
        </div>
        <br>
        </div>
    </main>

{% endblock %}