sistema/novidades/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from sistema import db
from sistema.novidades.models import Novidade
from datetime import datetime
import locale
try:
    locale.setlocale(locale.LC_ALL, 'pt_BR')
except:
    locale.setlocale(locale.LC_ALL, 'Portuguese_Brazil')

novidades = Blueprint('novidades', __name__, template_folder="templates")

@novidades.route('/')
def index():
    novidades = Novidade.query.order_by(Novidade.id.desc()).all()
    return render_template('novidades.html', novidades_front=novidades)


@novidades.route('/adicionar-novidade/', methods=['GET', 'POST'])
def adicionar_novidade():
    if request.method == 'POST':
        titulo = request.form['title']
        mensagem = request.form['mensagem']
        nome = request.form['nome']

        novidade = Novidade(titulo, mensagem, nome)
        db.session.add(novidade)
        datenow = datetime.utcnow()
        novidade.pub_date = datenow.strftime('%x')
        # split_date = novidade.pub_date.split(" ", 1)
        # novidade.pub_date = split_date[0].replace('-', '/')

        db.session.commit()
        return redirect(url_for('novidades.index'))

    return render_template('adicionar-novidade.html')


@novidades.route('/editar_novidade/<_id>', methods=['GET', 'POST'])
def editar_novidade(_id):
    novidade = Novidade.query.get_or_404(_id)

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['mensagem']
        author = request.form['nome']

        novidade.title = title
        novidade.content = content
        novidade.author = author

        db.session.commit()

        return redirect(url_for('novidades.index'))

    return render_template('editar_novidade.html', novidade=novidade)


@novidades.route('/excluir_novidade/<_id>', methods=['GET', 'POST'])
def excluir_novidade(_id):
    novidade = Novidade.query.get_or_404(_id)

    if request.method == 'POST':
        db.session.delete(novidade)
        db.session.commit()

        return redirect(url_for('novidades.index'))
    return render_template('excluir_novidade.html', novidade=novidade)

sistema/principal/views.py
from flask import Blueprint, render_template, request
from sistema.livros.models import Livro
from sistema.sedes.models import Sede
from sistema.novidades.models import Novidade
from sistema.livros.views import Livro
from sistema.sedes.views import Sede
from sistema.novidades.views import Novidade


principal = Blueprint('principal', __name__)


@principal.route('/', methods=['GET', 'POST'])
def index():
    sedes = Sede.query.order_by(Sede.id.desc()).all()
    livros = Livro.query.order_by(Livro.id.desc()).all()
    ultima_sede = Sede.query.order_by(Sede.id.asc()).first()
    return render_template('index.html',  ultima_sede = ultima_sede, livros=livros, sedes_front=sedes)


@principal.route('/contato/')
def contato():
    return render_template('contato.html')


@principal.route('/sobre/')
def sobre():
    return render_template('sobre.html')


## ROTA DE TESTE
@principal.route('/pesquisateste/')
def pesquisateste():
    result_livros = Livro.query.order_by(Livro.id.desc()).all()
    result_sedes = Sede.query.order_by(Sede.id.desc()).all()
    result_novidades = Novidade.query.order_by(Novidade.pub_date.desc()).all()
    # ÚLTIMA SEDE PARA RETIRAR A LINHA
    ultima_sede = Sede.query.order_by(Sede.id.asc()).first()
    return render_template('resultados.html', ultima_sede = ultima_sede, livros = result_livros, sedes = result_sedes, novidades = result_novidades)

@principal.route('/resultados/', methods=['GET', 'POST'])
def pesquisa():

    pesquisa = request.form['pesquisa']

    #resultados de livros pesquisados
    search_livros_title = Livro.query.filter(Livro.title.contains(str(pesquisa).strip().title())).all()
    search_livros_author = Livro.query.filter(Livro.author.contains(str(pesquisa).strip().title())).all()
    search_livros_gender = Livro.query.filter(Livro.gender.contains(str(pesquisa).strip().title())).all()

    titulo_l = set(search_livros_title)
    autor_l = set(search_livros_author)
    genero_l = set(search_livros_gender)

    interc_l1 = autor_l - genero_l
    apenas_autor = list(interc_l1) + search_livros_gender
    autor_e_genero_l = set(apenas_autor)
    interc_l2 = autor_e_genero_l - titulo_l

    livros_pesquisados =  list(interc_l2) + search_livros_title

    #resultados de sedes pesquisados
    search_sedes_nome = Sede.query.filter(Sede.name.contains(str(pesquisa).strip().title())).all()
    search_sede_endereco = Sede.query.filter(Sede.address.contains(str(pesquisa).strip().title())).all()
    nome_s = set(search_sedes_nome)
    endereco_s = set(search_sede_endereco)
    interc_s = endereco_s - nome_s
    sedes_pesquisadas =  list(interc_s) + search_sedes_nome

    #resultados de sedes pesquisados
    search_sedes_nome = Sede.query.filter(Sede.name.contains(str(pesquisa).strip().title())).all()
    search_sede_endereco = Sede.query.filter(Sede.address.contains(str(pesquisa).strip().title())).all()
    nome_s = set(search_sedes_nome)
    endereco_s = set(search_sede_endereco)
    interc_s = endereco_s - nome_s
    sedes_pesquisadas = list(interc_s) + search_sedes_nome

    #resultados de novidades pesquisadas
    search_novidades_titulo = Novidade.query.filter(Novidade.title.contains(str(pesquisa).strip().title())).all() 
    search_novidades_autor = Novidade.query.filter(Novidade.author.contains(str(pesquisa).strip().title())).all()
    search_novidades_texto = Novidade.query.filter(Novidade.content.contains(str(pesquisa).strip().title())).all()
    titulo_n = set(search_novidades_titulo)
    autor_n = set(search_novidades_autor)
    texto_n = set(search_novidades_texto)

    interc_n1 = texto_n - titulo_n
    title_no_repeat = list(interc_n1) + search_novidades_titulo
    titulo_e_texto_n = set(title_no_repeat)

    interc_n2 = titulo_e_texto_n - autor_n
    novidades_pesquisadas = list(interc_n2) + search_novidades_autor

    # ÚLTIMA SEDE PARA RETIRAR A LINHA
    if sedes_pesquisadas:
        ultima_sede = sedes_pesquisadas[len(sedes_pesquisadas)-1]
    else:
        ultima_sede = None

    return render_template('resultados.html', ultima_sede = ultima_sede, livros=livros_pesquisados, sedes=sedes_pesquisadas, novidades=novidades_pesquisadas)

sistema/sedes/views.py
import os
from flask import Blueprint, render_template, request, redirect, url_for
from sistema import app, db, allowed_image
from sistema.sedes.models import Sede
from werkzeug.utils import secure_filename

sedes = Blueprint('sedes', __name__, template_folder="templates")


@sedes.route('/')
def index():
    sedes = Sede.query.order_by(Sede.id.desc()).all()
    ultima_sede = Sede.query.order_by(Sede.id.asc()).first()
    return render_template('sedes.html', ultima_sede = ultima_sede, sedes_front=sedes)


@sedes.route('/adicionar-sede/', methods=['GET', 'POST'])
def adicionar_sede():
    if request.method == 'POST':
        sede_name = request.form['sede-name']
        sede_phone = request.form['contact']
        sede_address = request.form['address']
        sede_schedule = request.form['schedule']

        # PROCESSAMENTO DE IMAGEM
        image = request.files['myfile']

        if not allowed_image(image.filename):
            print("That image is not allowed")
            return redirect(url_for('sedes.adicionar_sede'))
        else:
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config["IMAGE_UPLOADS"], filename))
            new_sede = Sede(sede_name, sede_address, sede_phone, sede_schedule, filename)
            db.session.add(new_sede)
            db.session.commit()
            return redirect(url_for('sedes.index'))

    else:
        return render_template('adicionar-sede.html')


@sedes.route('/sede-especifica/<_id>', methods=['GET', 'POST'])
def sede_especifica(_id):
    sede = Sede.query.get_or_404(_id)

    return render_template('sede_esp.html', sede=sede)


@sedes.route('/editar_sede/<_id>', methods=['GET', 'POST'])
def editar_sede(_id):

    sede = Sede.query.get_or_404(_id)

    if request.method == 'POST':
        name = request.form['sede-name']
        address = request.form['address']
        contact = request.form['contact']
        schedule = request.form['schedule']

        # PROCESSAMENTO DE IMAGEM
        image = request.files['myfile']

        if not allowed_image(image.filename) and image:
            print("That image is not allowed")
            return redirect(url_for('sedes.editar_sede', _id = _id))
        elif image:
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config["IMAGE_UPLOADS"], filename))

            sede.name = name
            sede.address = address
            sede.contact = contact
            sede.schedule = schedule
            sede.picture = filename

            db.session.commit()

            return redirect(url_for('sedes.sede_especifica', _id=sede.id))
        
        else:
            sede.name = name
            sede.address = address
            sede.schedule = schedule
            sede.contact = contact

            db.session.commit()

            return redirect(url_for('sedes.sede_especifica', _id=sede.id))

    return render_template('editar_sede.html', sede=sede)


@sedes.route('/excluir_sede/<_id>', methods=['GET', 'POST'])
def excluir_sede(_id):
    sede = Sede.query.get_or_404(_id)

    if request.method == 'POST':
        db.session.delete(sede)
        db.session.commit()

        return redirect(url_for('sedes.index'))
    return render_template('excluir_sede.html', sede=sede)

sistema/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--stylesheets-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond&family=Cormorant:wght@500&family=Gelasio&family=Montserrat:wght@300&family=Playfair+Display+SC&family=Playfair+Display:wght@500&family=Varela+Round&display=swap" rel="stylesheet"> 
        <link rel="sortcut icon" href="{{url_for('static', filename='images/shortcut.png')}}" type="image/x-icon">
        <title>O Mundo de Sofia</title>
        {% block head %} {% endblock %}
    
    </head>

    <body>

        <header>
            <script src="https://kit.fontawesome.com/0ebbc74821.js" crossorigin="anonymous"></script>
            <!-- HEADER PRA PC -->
            <div class="pc-header">
                <div class="fixed-menu">
                    <nav>
                    <a href="{{url_for('principal.index')}}"><li class="nav-item">Home</li></a>
                    <a href="{{url_for('livros.index')}}"><li class="nav-item">Livros</li></a>
                    <a href="{{url_for('sedes.index')}}"><li class="nav-item">Sedes</li></a>
                    <a href="{{url_for('novidades.index')}}"><li class="nav-item">Novidades</li></a>
                    <a href="{{url_for('principal.contato')}}"><li class="nav-item">Contato</li></a>
                    <a href="{{url_for('principal.sobre')}}"><li class="nav-item">Sobre</li></a>
                    </nav>
                </div>
        
                <div class="logo-top">
                    <a href="{{url_for('principal.index')}}">
                        <img src="{{url_for('static', filename='images/logo_cleaner.png')}}" alt="logomarca" height= "100px" width= "auto" id="logo">
                    </a>
                </div>
                <!-- BARRA DE PESQUISA -->
                <div class="search-top">
                    <form action="{{url_for('principal.pesquisa')}}" method="POST">
                        <input type="text" name="pesquisa" placeholder="Pesquisar" style="height: 30px;">
                        <input type="submit" style="display: none;">
                    </form>
                </div>
                <div class="filler"></div>
            </div>
            <!-- HEADER MOBILE -->
            <div class="mobile-header">
                <div class="fixed-menu">
                    <div class="logo-mobile">
                        <a href="{{url_for('principal.index')}}">
                            <img src="{{url_for('static', filename='images/shortcut_white.png')}}" alt="logo mobile" height="60px" width="auto" id="logo">
                        </a>
                    </div>
                    <!-- BARRA DE PESQUISA MOBILE -->
                    <div class="pesquisa-mobile">
                        <form action="{{url_for('principal.pesquisa')}}" method="POST">
                            <input type="text" name="pesquisa" placeholder="Pesquisar" style="height: 30px;">
                            <input type="submit" style="display: none;">
                        </form>
                    </div>
                    <!-- DROPDOWN -->
                    <div class="dropdown drop-mobile">
                        <button class="btn btn-primary dropdown-toggle" id="menu1" type="button" data-toggle="dropdown"><i class="fas fa-align-justify"></i>
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('principal.index')}}">Home</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('livros.index')}}">Livros</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('sedes.index')}}">Sedes</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('novidades.index')}}">Novidades</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('principal.contato')}}">Contato</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url_for('principal.sobre')}}">Sobre</a></li>
                        </ul>
                    </div>
                </div>
                <div class="filler"></div>
            </div>
        </header>
        {% block body %} {% endblock %}

    </body>


</html>

sistema/templates/contato.html
{% extends 'base.html' %}

{% block body %}

    <div id="modal">
        <div class="content">
            <div id="contato-title">
                <h1 class="montserrat">Entre em contato com nossa empresa!</h1>
            </div>
            <p>sofia.freitas@ijunior     (31) 983885995</p>

            <form action="">
                <div class="input-wrapper">
                    <label for="nome">Nome Completo</label>
                    <input type="text" name="name" placeholder="Escreva seu nome aqui.">
                </div>

                <div class="input-wrapper">
                    <label for="telefone">Telefone</label>
                    <input type="text" name="Telefone" placeholder="(00)90000-0000">
                </div>

                <div class="input-wrapper">
                    <label for="Email">Email</label>
                    <input type="text" name="Email" placeholder="Insira seu email aqui.">
                
                <div class="input-wrapper">
                    <label for="mensagem">Digite uma mensagem</label>
                    <textarea name="mensagem" cols="30" rows="10" placeholder="Escreva sua mensagem."></textarea>
                </div>

                <input id="botao-enviar" class="btn btn-primary" type="submit" value="Enviar">
            </form>
            <br><br>
        </div>
    </div>

{% endblock %}

        

sistema/templates/index.html
{% extends 'base.html' %}

{% block body %}

    <main>
        <!--Div a seguir contem uma div com os livros recentes e outra com as sedes recentes-->
        <div class="container homepage">
            <div class="row" style="justify-content: center;">
                <h1 class="hometitle">
                    livros recentes
                </h1>
            </div>

            <div class="row" style="justify-content: center;">
                {% if not livros %}
                <h2>Ainda não há livros registrados</h2>
                {% endif %}
                {% for livro in livros[:3] %}
                <div class="col-sm-3 smaller-padding cards-livros-mobile">
                    <div class="card">  
                        <div class="card-body">
                            <div class="card-titulo">
                                <a class="no-dec" href="{{url_for('livros.livro_esp', _id=livro.id)}}"><p class="card-text">{{livro.title}}</p></a>
                            </div>
                            <div class="card-autor">
                                <p class="card-desc">{{livro.gender}} - {{livro.author}}</p>
                            </div>
                        </div>
                        <img src="{{url_for('static', filename='images/' + livro.cover)}}">
                        <div class="card-body">
                            <p class="card-text">{{livro.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row" style="justify-content: center;">
                <h1 class="hometitle hometitle-mobile" style="padding-top: 30px;">
                    sedes recentes
                </h1>
            </div>
            <div>
                {% if not sedes_front %}
                    <div class="row" style="justify-content: center;">
                        <h2>Ainda não há sedes registradas</h2>
                    </div>
                {% endif %}
                {% for sede in sedes_front[:3] %}
                <div class="sede-mobile" {% if sede == sedes_front[2] %} style="border-bottom: none;" {% endif %}>
                    <a class="nome-sedes" href="{{url_for('sedes.sede_especifica', _id=sede.id)}}">
                        <h3>{{sede.name}}</h3>
                    </a>
                    <p>{{sede.address}}</p>
                    <p>{{sede.contact}}</p>
                    <div class="editar-excluir-sedes">
                        <button type="button" class="btn btn-primary"><a href="{{url_for('sedes.editar_sede', _id=sede.id)}}">Editar</a></button></a>
                        <button type="button" class="btn btn-primary excluir-sedes"><a href="{{url_for('sedes.excluir_sede', _id=sede.id)}}">Excluir</a></button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </main>

{% endblock %}

sistema/templates/resultados.html
{% extends 'base.html' %}

{% block title %}
Resultados da pesquisa
{% endblock %}

{% block body %}
<div class="container results">
    <h2 style="text-align: center;">Resultados da pesquisa:</h2>
    <br><br>
    <h2 class="montserrat">Livros</h2>
    <br>
    <!-- For com um card para cada livro -->
        {% if not livros %}
        <h4>Não foram encontrados livros para sua pesquisa.</h4>
        {% endif %}
        <div class="row row-mobile borderbottom" style="padding-left: 6px;">
            {% for livro in livros %}

            <div class="col-sm-3 smaller-padding cards-livros-mobile">
                <div class="card">  
                    <div class="card-body">
                        <div class="card-titulo">
                            <a class="no-dec" href="{{url_for('livros.livro_esp', _id=livro.id)}}"><p class="card-text">{{livro.title}}</p></a>
                        </div>
                        <div class="card-autor">
                            <p class="card-desc">{{livro.gender}} - {{livro.author}}</p>
                        </div>
                    </div>
                    <img src="{{url_for('static', filename='images/' + livro.cover)}}">
                    <div class="card-body">
                        <p class="card-text">{{livro.price}}</p>
                    </div>
                </div>
            </div>

            {% endfor %}


        </div>
        
    <!-- Tabela com uma row para cada sede -->
    <br>
    <h2 class="montserrat">Sedes</h2>
    <div class="borderbottom">
        {% if not sedes %}
        <br>
        <h4>Não foram encontradas sedes para sua pesquisa.</h4>
        {% endif %}

        {% for sede in sedes %}           
        <div class="sede-mobile" {% if sede == ultima_sede %} style="border-bottom: none;" {% endif %}>
            <a class="nome-sedes" href="{{url_for('sedes.sede_especifica', _id=sede.id)}}">
                <h3>{{sede.name}}</h3>
            </a>
            <p>{{sede.address}}</p>
            <p>{{sede.contact}}</p>
            <div class="editar-excluir-sedes">
                <button type="button" class="btn btn-primary"><a href="{{url_for('sedes.editar_sede', _id=sede.id)}}">Editar</a></button></a>
                <button type="button" class="btn btn-primary excluir-sedes"><a href="{{url_for('sedes.excluir_sede', _id=sede.id)}}">Excluir</a></button>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Novidades -->
    <br>
    <h2 class="montserrat">Novidades</h2>
    <br>
    <div class="col-sm-12 borderbottom" style="padding-left: 0px;">
        {% if not novidades %}
        <h4>Não foram encontradas novidades para sua pesquisa.</h4>
        {% endif %}
        {% for novidade in novidades %}
        <div class="novidade">
            <h4>{{novidade.title}}</h4>
            <p>{{novidade.content}}</p>
            <div class="nome-data-novidade">
                <p><strong>{{novidade.author}}, {{novidade.pub_date}}</strong></p>
                
                <a href="{{url_for('novidades.editar_novidade', _id=novidade.id)}}" class="button-link"><button type="button" class="btn btn-primary">Editar</button></a>
                <a href="{{url_for('novidades.excluir_novidade', _id=novidade.id)}}" class="button-link"><button type="button" class="btn btn-primary">Excluir</button></a>
                
            </div>
            <br class="mobile-header">
        {% endfor %}
    </div>
</div>
{% endblock %}

sistema/templates/sobre.html
{% extends 'base.html' %}

{% block body %}

    <main>
        <div class="container about about-container">
                    <div class="row align-content-sm-center align-content-md-center align-content-lg-center">
                        <div class="col-sm-6">
                                <img src="{{url_for('static', filename='images/O_mundo_de_sofia_sobre.jpg')}}" class="img-fluid rounded">
                                <br><br>
                        </div>
                        <div class="col-sm-6">
                                <p style="text-align: justify; font-size: 1.2rem;">
                                    Inspirado no Livro 'O Mundo de Sofia' escrito por Jostein Gaarder em 1991 e primeira edição em português em 1995, a livraria foi fundada em 2000 ( 9 anos após o lançamento oficial e 5 anos após o lançamento traduzido), com o objetivo de fomentar a sede de conhecimento e fomentar a leitura entre as pessoas. O romance escrito por Jostein aborda importantes aspectos da filosofia e muitos pontos para reflexão no geral, sendo assim, uma enorme inspiração para mim, Hilde, a fundadora dessa livraria. Atualmente temos 3 sedes físicas em Belo Horizonte - Minas Gerais e somos muito mais do que só uma livraria, mas sim, um lugar de aprendizagem, inspiração e reflexão. Desejo a todos uma ótima leitura. 
                                    <br>
                                </p> 
                            <div style="display: block; text-align: right">
                                    <p>
                                        Atenciosamente, 
                                        <br>Hilde.
                                    </p>
                            </div>
                        </div>
                    </div>
        </div>
    </main>

{% endblock %}